"""add_probe_groups

Revision ID: 283efc2c973a
Revises: d61cfbdf8a24
Create Date: 2026-03-21 21:32:15.974895

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '283efc2c973a'
down_revision: Union[str, None] = 'd61cfbdf8a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probe_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_probe_groups_id'), 'probe_groups', ['id'], unique=False)
    op.create_table('probe_group_members',
    sa.Column('probe_group_id', sa.Uuid(), nullable=False),
    sa.Column('probe_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['probe_group_id'], ['probe_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['probe_id'], ['probes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('probe_group_id', 'probe_id')
    )
    op.create_table('user_probe_group_access',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('probe_group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['probe_group_id'], ['probe_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'probe_group_id')
    )
    # NOTE: auto-generated migration originally dropped maintenance_windows and
    # audit_logs here.  Those tables are still in use — removed the drop statements.
    op.alter_column('alert_rules', 'schedule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_annotations_monitor_id'), table_name='monitor_annotations')
    op.create_index(op.f('ix_monitor_annotations_monitor_id'), 'monitor_annotations', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_monitor_templates_id'), 'monitor_templates', ['id'], unique=False)
    op.create_index(op.f('ix_monitor_templates_owner_id'), 'monitor_templates', ['owner_id'], unique=False)
    op.alter_column('monitors', 'heartbeat_grace_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('60'))
    op.drop_index(op.f('ix_monitors_heartbeat_slug'), table_name='monitors')
    op.drop_index(op.f('ix_status_subscriptions_group_email'), table_name='status_subscriptions')
    op.create_index(op.f('ix_user_api_keys_id'), 'user_api_keys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_keys_id'), table_name='user_api_keys')
    op.create_index(op.f('ix_status_subscriptions_group_email'), 'status_subscriptions', ['group_id', 'email'], unique=True)
    op.create_index(op.f('ix_monitors_heartbeat_slug'), 'monitors', ['heartbeat_slug'], unique=True)
    op.alter_column('monitors', 'heartbeat_grace_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('60'))
    op.drop_index(op.f('ix_monitor_templates_owner_id'), table_name='monitor_templates')
    op.drop_index(op.f('ix_monitor_templates_id'), table_name='monitor_templates')
    op.drop_index(op.f('ix_monitor_annotations_monitor_id'), table_name='monitor_annotations')
    op.create_index(op.f('ix_annotations_monitor_id'), 'monitor_annotations', ['monitor_id'], unique=False)
    op.alter_column('alert_rules', 'schedule',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # NOTE: corresponding downgrade for removed drop statements — tables are kept.
    op.drop_table('user_probe_group_access')
    op.drop_table('probe_group_members')
    op.drop_index(op.f('ix_probe_groups_id'), table_name='probe_groups')
    op.drop_table('probe_groups')
    # ### end Alembic commands ###
