"""add_probe_groups

Revision ID: 283efc2c973a
Revises: d61cfbdf8a24
Create Date: 2026-03-21 21:32:15.974895

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '283efc2c973a'
down_revision: Union[str, None] = 'd61cfbdf8a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probe_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_probe_groups_id'), 'probe_groups', ['id'], unique=False)
    op.create_table('probe_group_members',
    sa.Column('probe_group_id', sa.Uuid(), nullable=False),
    sa.Column('probe_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['probe_group_id'], ['probe_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['probe_id'], ['probes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('probe_group_id', 'probe_id')
    )
    op.create_table('user_probe_group_access',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('probe_group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['probe_group_id'], ['probe_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'probe_group_id')
    )
    op.drop_index(op.f('ix_maintenance_windows_group_id'), table_name='maintenance_windows')
    op.drop_index(op.f('ix_maintenance_windows_monitor_id'), table_name='maintenance_windows')
    op.drop_index(op.f('ix_maintenance_windows_owner_id'), table_name='maintenance_windows')
    op.drop_table('maintenance_windows')
    op.drop_index(op.f('ix_audit_logs_object'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.alter_column('alert_rules', 'schedule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_annotations_monitor_id'), table_name='monitor_annotations')
    op.create_index(op.f('ix_monitor_annotations_monitor_id'), 'monitor_annotations', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_monitor_templates_id'), 'monitor_templates', ['id'], unique=False)
    op.create_index(op.f('ix_monitor_templates_owner_id'), 'monitor_templates', ['owner_id'], unique=False)
    op.alter_column('monitors', 'heartbeat_grace_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('60'))
    op.drop_index(op.f('ix_monitors_heartbeat_slug'), table_name='monitors')
    op.drop_index(op.f('ix_status_subscriptions_group_email'), table_name='status_subscriptions')
    op.create_index(op.f('ix_user_api_keys_id'), 'user_api_keys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_keys_id'), table_name='user_api_keys')
    op.create_index(op.f('ix_status_subscriptions_group_email'), 'status_subscriptions', ['group_id', 'email'], unique=True)
    op.create_index(op.f('ix_monitors_heartbeat_slug'), 'monitors', ['heartbeat_slug'], unique=True)
    op.alter_column('monitors', 'heartbeat_grace_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('60'))
    op.drop_index(op.f('ix_monitor_templates_owner_id'), table_name='monitor_templates')
    op.drop_index(op.f('ix_monitor_templates_id'), table_name='monitor_templates')
    op.drop_index(op.f('ix_monitor_annotations_monitor_id'), table_name='monitor_annotations')
    op.create_index(op.f('ix_annotations_monitor_id'), 'monitor_annotations', ['monitor_id'], unique=False)
    op.alter_column('alert_rules', 'schedule',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('object_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('object_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('diff', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_object'), 'audit_logs', ['object_type', 'object_id'], unique=False)
    op.create_table('maintenance_windows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('monitor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('starts_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ends_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('suppress_alerts', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['monitor_groups.id'], name=op.f('maintenance_windows_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('maintenance_windows_monitor_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('maintenance_windows_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_windows_pkey'))
    )
    op.create_index(op.f('ix_maintenance_windows_owner_id'), 'maintenance_windows', ['owner_id'], unique=False)
    op.create_index(op.f('ix_maintenance_windows_monitor_id'), 'maintenance_windows', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_maintenance_windows_group_id'), 'maintenance_windows', ['group_id'], unique=False)
    op.drop_table('user_probe_group_access')
    op.drop_table('probe_group_members')
    op.drop_index(op.f('ix_probe_groups_id'), table_name='probe_groups')
    op.drop_table('probe_groups')
    # ### end Alembic commands ###
