"""initial

Revision ID: 76f1c42af699
Revises: 
Create Date: 2026-03-01 00:09:11.534900

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '76f1c42af699'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('api_key_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probes_id'), 'probes', ['id'], unique=False)
    op.create_index(op.f('ix_probes_is_active'), 'probes', ['is_active'], unique=False)
    op.create_index(op.f('ix_probes_name'), 'probes', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alert_channels',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('email', 'webhook', 'telegram', name='alert_channel_type'),
        nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_channels_id'), 'alert_channels', ['id'], unique=False)
    op.create_index(
        op.f('ix_alert_channels_owner_id'), 'alert_channels', ['owner_id'], unique=False
    )
    op.create_table('monitor_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public_slug', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_groups_id'), 'monitor_groups', ['id'], unique=False)
    op.create_index(
        op.f('ix_monitor_groups_owner_id'), 'monitor_groups', ['owner_id'], unique=False
    )
    op.create_index(
        op.f('ix_monitor_groups_public_slug'), 'monitor_groups', ['public_slug'], unique=True
    )
    op.create_table('user_tag_permissions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Enum('view', 'edit', 'admin', name='permission_level'),
        nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    op.create_index('ix_utp_tag_id', 'user_tag_permissions', ['tag_id'], unique=False)
    op.create_index('ix_utp_user_id', 'user_tag_permissions', ['user_id'], unique=False)
    op.create_table('monitor_group_tags',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['monitor_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'tag_id')
    )
    op.create_table('monitors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('follow_redirects', sa.Boolean(), nullable=False),
    sa.Column('expected_status_codes', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('ssl_check_enabled', sa.Boolean(), nullable=False),
    sa.Column('ssl_expiry_warn_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['monitor_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitors_enabled'), 'monitors', ['enabled'], unique=False)
    op.create_index('ix_monitors_enabled_owner', 'monitors', ['enabled', 'owner_id'], unique=False)
    op.create_index(op.f('ix_monitors_group_id'), 'monitors', ['group_id'], unique=False)
    op.create_index(op.f('ix_monitors_id'), 'monitors', ['id'], unique=False)
    op.create_index(op.f('ix_monitors_owner_id'), 'monitors', ['owner_id'], unique=False)
    op.create_table('public_pages',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['monitor_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_pages_group_id'), 'public_pages', ['group_id'], unique=False)
    op.create_index(op.f('ix_public_pages_id'), 'public_pages', ['id'], unique=False)
    op.create_index(op.f('ix_public_pages_slug'), 'public_pages', ['slug'], unique=True)
    op.create_table('alert_rules',
    sa.Column('monitor_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column(
        'condition',
        sa.Enum('all_down', 'any_down', 'ssl_expiry', name='alert_condition'),
        nullable=False,
    ),
    sa.Column('min_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['monitor_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_group_id'), 'alert_rules', ['group_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_alert_rules_monitor_id'), 'alert_rules', ['monitor_id'], unique=False)
    op.create_table('check_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('probe_id', sa.Uuid(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column(
        'status', sa.Enum('up', 'down', 'timeout', 'error', name='check_status'), nullable=False
    ),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('redirect_count', sa.Integer(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('ssl_valid', sa.Boolean(), nullable=True),
    sa.Column('ssl_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ssl_days_remaining', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['probe_id'], ['probes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_cr_monitor_checked_at', 'check_results', ['monitor_id', 'checked_at'], unique=False
    )
    op.create_index(
        'ix_cr_probe_checked_at', 'check_results', ['probe_id', 'checked_at'], unique=False
    )
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('scope', sa.Enum('global_', 'geographic', name='incident_scope'), nullable=False),
    sa.Column('affected_probe_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_incidents_monitor_started', 'incidents', ['monitor_id', 'started_at'], unique=False
    )
    op.create_index('ix_incidents_resolved', 'incidents', ['resolved_at'], unique=False)
    op.create_table('monitor_tags',
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monitor_id', 'tag_id')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', name='alert_event_status'), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['alert_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_events_incident', 'alert_events', ['incident_id'], unique=False)
    op.create_index('ix_alert_events_sent_at', 'alert_events', ['sent_at'], unique=False)
    op.create_table('alert_rule_channels',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['alert_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'channel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_rule_channels')
    op.drop_index('ix_alert_events_sent_at', table_name='alert_events')
    op.drop_index('ix_alert_events_incident', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_table('monitor_tags')
    op.drop_index('ix_incidents_resolved', table_name='incidents')
    op.drop_index('ix_incidents_monitor_started', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_cr_probe_checked_at', table_name='check_results')
    op.drop_index('ix_cr_monitor_checked_at', table_name='check_results')
    op.drop_table('check_results')
    op.drop_index(op.f('ix_alert_rules_monitor_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_group_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_public_pages_slug'), table_name='public_pages')
    op.drop_index(op.f('ix_public_pages_id'), table_name='public_pages')
    op.drop_index(op.f('ix_public_pages_group_id'), table_name='public_pages')
    op.drop_table('public_pages')
    op.drop_index(op.f('ix_monitors_owner_id'), table_name='monitors')
    op.drop_index(op.f('ix_monitors_id'), table_name='monitors')
    op.drop_index(op.f('ix_monitors_group_id'), table_name='monitors')
    op.drop_index('ix_monitors_enabled_owner', table_name='monitors')
    op.drop_index(op.f('ix_monitors_enabled'), table_name='monitors')
    op.drop_table('monitors')
    op.drop_table('monitor_group_tags')
    op.drop_index('ix_utp_user_id', table_name='user_tag_permissions')
    op.drop_index('ix_utp_tag_id', table_name='user_tag_permissions')
    op.drop_table('user_tag_permissions')
    op.drop_index(op.f('ix_monitor_groups_public_slug'), table_name='monitor_groups')
    op.drop_index(op.f('ix_monitor_groups_owner_id'), table_name='monitor_groups')
    op.drop_index(op.f('ix_monitor_groups_id'), table_name='monitor_groups')
    op.drop_table('monitor_groups')
    op.drop_index(op.f('ix_alert_channels_owner_id'), table_name='alert_channels')
    op.drop_index(op.f('ix_alert_channels_id'), table_name='alert_channels')
    op.drop_table('alert_channels')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_probes_name'), table_name='probes')
    op.drop_index(op.f('ix_probes_is_active'), table_name='probes')
    op.drop_index(op.f('ix_probes_id'), table_name='probes')
    op.drop_table('probes')
    # ### end Alembic commands ###
