"""On-call rotations, escalation policies and user contacts (plan V2, B-0).

Revision ID: c4d5e6f7a8b9
Revises: f2a3b4c5d6e7
Create Date: 2026-07-29

Adds the person-centred half of the alert stack: who is on call
(``oncall_schedules`` + participants + overrides), in what order they get paged
(``escalation_policies`` + ``escalation_levels``), and how to reach them
(``user_contacts``). ``alert_rules.escalation_policy_id`` is the opt-in switch —
NULL keeps the historical channel fan-out plus renotify.

Hand-written rather than autogenerated: `alembic revision --autogenerate` also
proposes dropping ``audit_logs`` and ``maintenance_windows`` (their models are
not imported in ``whatisup/models/__init__.py``) plus a dozen unrelated index
and JSON-type changes. That divergence predates this work and is left alone.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c4d5e6f7a8b9"
down_revision: str | None = "f2a3b4c5d6e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ENUM_TYPES = ("contact_method", "rotation_type", "escalation_target_type")


def upgrade() -> None:
    op.create_table(
        "user_contacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "email",
                "push",
                "telegram",
                "slack",
                "discord",
                "mattermost",
                "signal",
                name="contact_method",
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("via_channel_id", sa.Uuid(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["via_channel_id"], ["alert_channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "method", "value", name="uq_user_contact_method_value"),
    )
    op.create_index("ix_user_contacts_id", "user_contacts", ["id"])
    op.create_index("ix_user_contacts_user_id", "user_contacts", ["user_id"])

    op.create_table(
        "oncall_schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column(
            "rotation_type",
            sa.Enum("daily", "weekly", "custom_days", name="rotation_type"),
            nullable=False,
        ),
        sa.Column("rotation_length_days", sa.Integer(), server_default="7", nullable=False),
        sa.Column("handoff_time", sa.String(length=5), server_default="09:00", nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rotation_length_days > 0", name="ck_oncall_rotation_length_positive"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_oncall_schedules_id", "oncall_schedules", ["id"])
    op.create_index("ix_oncall_schedules_owner_id", "oncall_schedules", ["owner_id"])
    op.create_index("ix_oncall_schedules_team_id", "oncall_schedules", ["team_id"])

    op.create_table(
        "oncall_participants",
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["schedule_id"], ["oncall_schedules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        # (schedule_id, user_id) as PK already indexes schedule_id — no extra index.
        sa.PrimaryKeyConstraint("schedule_id", "user_id"),
        sa.UniqueConstraint("schedule_id", "position", name="uq_oncall_participant_position"),
    )

    op.create_table(
        "oncall_overrides",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("ends_at > starts_at", name="ck_oncall_override_window"),
        sa.ForeignKeyConstraint(["schedule_id"], ["oncall_schedules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_oncall_overrides_id", "oncall_overrides", ["id"])
    op.create_index(
        "ix_oncall_overrides_lookup",
        "oncall_overrides",
        ["schedule_id", "starts_at", "ends_at"],
    )

    op.create_table(
        "escalation_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("repeat_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("repeat_count >= 0", name="ck_escalation_repeat_non_negative"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_escalation_policies_id", "escalation_policies", ["id"])
    op.create_index("ix_escalation_policies_owner_id", "escalation_policies", ["owner_id"])
    op.create_index("ix_escalation_policies_team_id", "escalation_policies", ["team_id"])

    op.create_table(
        "escalation_levels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("delay_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum("channel", "schedule", "user", name="escalation_target_type"),
            nullable=False,
        ),
        sa.Column("target_channel_id", sa.Uuid(), nullable=True),
        sa.Column("target_schedule_id", sa.Uuid(), nullable=True),
        sa.Column("target_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("delay_minutes >= 0", name="ck_escalation_delay_non_negative"),
        # The discriminator and the FK columns must agree, enforced by the
        # database and not only by Pydantic: a level claiming target_type
        # 'schedule' while only target_channel_id is set would page nobody,
        # silently — the worst failure mode an on-call ladder can have.
        sa.CheckConstraint(
            "(target_type = 'channel' AND target_channel_id IS NOT NULL "
            "AND target_schedule_id IS NULL AND target_user_id IS NULL) OR "
            "(target_type = 'schedule' AND target_schedule_id IS NOT NULL "
            "AND target_channel_id IS NULL AND target_user_id IS NULL) OR "
            "(target_type = 'user' AND target_user_id IS NOT NULL "
            "AND target_channel_id IS NULL AND target_schedule_id IS NULL)",
            name="ck_escalation_level_single_target",
        ),
        sa.ForeignKeyConstraint(["policy_id"], ["escalation_policies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_channel_id"], ["alert_channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["target_schedule_id"], ["oncall_schedules.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # uq_… leads with policy_id, so fetching a policy's ladder is covered.
        sa.UniqueConstraint("policy_id", "position", name="uq_escalation_level_position"),
    )
    op.create_index("ix_escalation_levels_id", "escalation_levels", ["id"])

    # Opt-in switch. SET NULL, never CASCADE: deleting a policy must degrade the
    # rule to the legacy channel fan-out, not delete the alert rule with it.
    op.add_column("alert_rules", sa.Column("escalation_policy_id", sa.Uuid(), nullable=True))
    op.create_index("ix_alert_rules_escalation_policy_id", "alert_rules", ["escalation_policy_id"])
    op.create_foreign_key(
        "fk_alert_rules_escalation_policy_id",
        "alert_rules",
        "escalation_policies",
        ["escalation_policy_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint("fk_alert_rules_escalation_policy_id", "alert_rules", type_="foreignkey")
    op.drop_index("ix_alert_rules_escalation_policy_id", table_name="alert_rules")
    op.drop_column("alert_rules", "escalation_policy_id")

    op.drop_index("ix_escalation_levels_id", table_name="escalation_levels")
    op.drop_table("escalation_levels")

    op.drop_index("ix_escalation_policies_team_id", table_name="escalation_policies")
    op.drop_index("ix_escalation_policies_owner_id", table_name="escalation_policies")
    op.drop_index("ix_escalation_policies_id", table_name="escalation_policies")
    op.drop_table("escalation_policies")

    op.drop_index("ix_oncall_overrides_lookup", table_name="oncall_overrides")
    op.drop_index("ix_oncall_overrides_id", table_name="oncall_overrides")
    op.drop_table("oncall_overrides")

    op.drop_table("oncall_participants")

    op.drop_index("ix_oncall_schedules_team_id", table_name="oncall_schedules")
    op.drop_index("ix_oncall_schedules_owner_id", table_name="oncall_schedules")
    op.drop_index("ix_oncall_schedules_id", table_name="oncall_schedules")
    op.drop_table("oncall_schedules")

    op.drop_index("ix_user_contacts_user_id", table_name="user_contacts")
    op.drop_index("ix_user_contacts_id", table_name="user_contacts")
    op.drop_table("user_contacts")

    # PostgreSQL keeps enum types after their last table is dropped; without this
    # a downgrade followed by an upgrade fails on "type already exists".
    if op.get_bind().dialect.name == "postgresql":
        for enum_name in _ENUM_TYPES:
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
