"""Scheduled SLA report generation and email delivery."""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import aiosmtplib
from sqlalchemy import select

from whatisup.core.config import get_settings
from whatisup.models.monitor import Monitor, MonitorGroup

logger = logging.getLogger(__name__)


async def generate_group_report(db, group: MonitorGroup) -> str:
    """Generate HTML SLA report for a monitor group."""
    from whatisup.services.stats import compute_uptime

    period_days = 7 if group.report_schedule == "weekly" else 30
    period_label = "Weekly" if group.report_schedule == "weekly" else "Monthly"

    monitors = (
        await db.execute(
            select(Monitor).where(Monitor.group_id == group.id, Monitor.enabled.is_(True))
        )
    ).scalars().all()

    rows_html = ""
    for m in monitors:
        uptime = await compute_uptime(db, m.id, days=period_days)
        color = "#34d399" if uptime >= 99 else "#fbbf24" if uptime >= 95 else "#f87171"
        rows_html += (
            f'<tr>'
            f'<td style="padding:8px 12px;border-bottom:1px solid #1e2d3d;color:#e4ecf4;">'
            f'{m.name}</td>'
            f'<td style="padding:8px 12px;border-bottom:1px solid #1e2d3d;color:#e4ecf4;">'
            f'{m.check_type}</td>'
            f'<td style="padding:8px 12px;border-bottom:1px solid #1e2d3d;'
            f'color:{color};font-weight:600;">{uptime:.2f}%</td>'
            f'</tr>'
        )

    html = (
        '<!DOCTYPE html>'
        '<html>'
        '<body style="background:#0c1117;color:#e4ecf4;font-family:system-ui,sans-serif;'
        'padding:32px;">'
        '<div style="max-width:600px;margin:0 auto;">'
        f'<h1 style="font-size:20px;color:#4f9cf9;margin-bottom:4px;">'
        f'WhatIsUp &mdash; {period_label} SLA Report</h1>'
        f'<p style="font-size:13px;color:#8899aa;margin-bottom:24px;">'
        f'Group: <strong>{group.name}</strong> &mdash; '
        f'{datetime.now(UTC).strftime("%Y-%m-%d")}</p>'
        '<table style="width:100%;border-collapse:collapse;background:#131920;'
        'border-radius:8px;overflow:hidden;">'
        '<thead><tr style="border-bottom:2px solid #1e2d3d;">'
        '<th style="padding:10px 12px;text-align:left;font-size:11px;color:#4d6070;'
        'text-transform:uppercase;">Monitor</th>'
        '<th style="padding:10px 12px;text-align:left;font-size:11px;color:#4d6070;'
        'text-transform:uppercase;">Type</th>'
        '<th style="padding:10px 12px;text-align:left;font-size:11px;color:#4d6070;'
        'text-transform:uppercase;">Uptime</th>'
        '</tr></thead>'
        f'<tbody>{rows_html}</tbody></table>'
        f'<p style="font-size:11px;color:#4d6070;margin-top:16px;text-align:center;">'
        f'Generated by WhatIsUp on {datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")}</p>'
        '</div></body></html>'
    )
    return html


async def send_report_email(emails: list[str], subject: str, html_body: str) -> None:
    """Send report email via SMTP using existing infrastructure."""
    settings = get_settings()
    if not settings.smtp_host:
        logger.warning("report_email_skipped_no_smtp")
        return

    for recipient in emails:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = settings.smtp_from
        msg["To"] = recipient
        msg.attach(MIMEText(html_body, "html"))

        try:
            await aiosmtplib.send(
                msg,
                hostname=settings.smtp_host,
                port=settings.smtp_port,
                start_tls=settings.smtp_tls,
                username=settings.smtp_user or None,
                password=settings.smtp_password or None,
                timeout=15,
            )
        except Exception as exc:
            logger.error(
                "report_email_failed",
                extra={"recipient": recipient, "error_type": type(exc).__name__},
            )


async def check_and_send_reports() -> None:
    """Check which groups are due for a report and send them."""
    from whatisup.core.database import get_session_factory

    now = datetime.now(UTC)
    weekday = now.weekday()  # 0=Monday
    day = now.day
    hour = now.hour

    # Only run at 08:00 UTC
    if hour != 8:
        return

    async with get_session_factory()() as db:
        groups = (
            await db.execute(
                select(MonitorGroup).where(MonitorGroup.report_schedule.isnot(None))
            )
        ).scalars().all()

        for group in groups:
            if not group.report_emails:
                continue

            send = False
            if group.report_schedule == "weekly" and weekday == 0:
                send = True
            elif group.report_schedule == "monthly" and day == 1:
                send = True

            if not send:
                continue

            try:
                html = await generate_group_report(db, group)
                period = "Weekly" if group.report_schedule == "weekly" else "Monthly"
                subject = f"WhatIsUp {period} SLA Report — {group.name}"
                await send_report_email(group.report_emails, subject, html)
                logger.info(
                    "report_sent",
                    extra={"group": group.name, "schedule": group.report_schedule},
                )
            except Exception as exc:
                logger.error(
                    "report_generation_failed",
                    extra={"group": group.name, "error_type": type(exc).__name__},
                )
