"""Fail if the ORM metadata and the migrated schema have drifted apart.

Run against a database already at ``head``::

    cd server
    DATABASE_URL=postgresql+asyncpg://... python scripts/check_model_drift.py

``alembic revision --autogenerate`` is only trustworthy when it has nothing to
say about an up-to-date database. Left unchecked, the noise accumulates — a
model that never made it into ``models/__init__.py``, an index created by
migration but never declared, a column typed one way in Python and another in
PostgreSQL — until a genuine diff is indistinguishable from the twenty-odd
false ones and autogenerate stops being usable at all. This is the guard that
keeps that count at zero; migration ``d5e6f7a8b9c0`` is the cleanup that got it
there.
"""

from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

# Compare against *this* checkout, not whatever copy of ``whatisup`` happens to
# be installed in site-packages. Getting this wrong does not raise — it silently
# compares the schema against a stale package and invents differences.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from alembic.autogenerate import compare_metadata  # noqa: E402
from alembic.migration import MigrationContext  # noqa: E402
from sqlalchemy import Connection  # noqa: E402
from sqlalchemy.ext.asyncio import create_async_engine  # noqa: E402

from whatisup.models import Base  # noqa: E402


def _compare(connection: Connection) -> list:
    context = MigrationContext.configure(connection, opts={"compare_type": True})
    return compare_metadata(context, Base.metadata)


async def main() -> int:
    url = os.environ.get("DATABASE_URL")
    if not url:
        print("DATABASE_URL is required", file=sys.stderr)
        return 2

    engine = create_async_engine(url)
    try:
        async with engine.connect() as connection:
            diffs = await connection.run_sync(_compare)
    finally:
        await engine.dispose()

    if not diffs:
        print("No drift: the ORM metadata matches the migrated schema.")
        return 0

    print(f"{len(diffs)} difference(s) between the models and the schema:", file=sys.stderr)
    for diff in diffs:
        print(f"  - {diff}", file=sys.stderr)
    print(
        "\nEither the models changed without a migration, or a migration changed the "
        "schema without the models. Fix whichever side is wrong — do not commit the "
        "autogenerated output blindly.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
