// Plan cap v2, 6b — replacement for the browser extension recorder: import a
// script generated by `playwright codegen` (https://playwright.dev/docs/codegen)
// into ScenarioBuilder's step list, instead of recording it live.
//
// Best-effort by design: codegen emits `getByRole`/`getByText`/... locators,
// which don't map onto a single CSS selector 1:1. We convert them using only
// standard CSS plus Playwright's documented `:has-text()` extension and its
// `text=` selector engine (both stable public API — no reliance on internal,
// unstable selector engines). The README tells the user to review selectors
// before saving; this module surfaces what it could not translate as
// warnings rather than silently dropping or guessing wrong.

const ROLE_TO_CSS = {
  button: 'button, [role="button"], input[type=button], input[type=submit]',
  link: 'a, [role="link"]',
  textbox: 'input, textarea, [role="textbox"]',
  checkbox: 'input[type=checkbox], [role="checkbox"]',
  radio: 'input[type=radio], [role="radio"]',
  combobox: 'select, [role="combobox"]',
  heading: 'h1, h2, h3, h4, h5, h6, [role="heading"]',
  img: 'img, [role="img"]',
  listitem: 'li, [role="listitem"]',
  list: 'ul, ol, [role="list"]',
  option: 'option, [role="option"]',
  tab: '[role="tab"]',
  menuitem: '[role="menuitem"]',
  dialog: '[role="dialog"]',
  alert: '[role="alert"]',
}

const LOCATOR_METHODS = new Set([
  'getByRole', 'getByText', 'getByLabel', 'getByPlaceholder',
  'getByAltText', 'getByTitle', 'getByTestId', 'locator',
])
const MODIFIER_METHODS = new Set(['first', 'last', 'nth'])

function escAttr(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function hasText(base, text) {
  return text ? `${base}:has-text("${escAttr(text)}")` : base
}

// Walk a string tracking paren/brace/bracket depth and quotes; used both to
// split a chain on top-level `.` and to split call args on top-level `,`.
function splitTopLevel(str, sep) {
  const parts = []
  let depth = 0
  let inStr = null
  let start = 0
  for (let i = 0; i < str.length; i++) {
    const c = str[i]
    if (inStr) {
      if (c === '\\') { i++; continue }
      if (c === inStr) inStr = null
      continue
    }
    if (c === "'" || c === '"' || c === '`') { inStr = c; continue }
    if (c === '(' || c === '{' || c === '[') depth++
    else if (c === ')' || c === '}' || c === ']') depth--
    else if (c === sep && depth === 0) {
      parts.push(str.slice(start, i))
      start = i + 1
    }
  }
  parts.push(str.slice(start))
  return parts
}

function findMatchingParen(str, openIdx) {
  let depth = 0
  let inStr = null
  for (let i = openIdx; i < str.length; i++) {
    const c = str[i]
    if (inStr) {
      if (c === '\\') { i++; continue }
      if (c === inStr) inStr = null
      continue
    }
    if (c === "'" || c === '"' || c === '`') { inStr = c; continue }
    if (c === '(') depth++
    else if (c === ')') { depth--; if (depth === 0) return i }
  }
  return -1
}

function firstStringArg(args) {
  if (!args) return null
  const m = args.match(/^\s*['"`]((?:\\.|[^'"`\\])*)['"`]/)
  if (!m) return null
  return m[1].replace(/\\(.)/g, '$1')
}

function namedOptionArg(args, key) {
  if (!args) return null
  const re = new RegExp(key + "\\s*:\\s*['\"`]((?:\\\\.|[^'\"`\\\\])*)['\"`]")
  const m = args.match(re)
  return m ? m[1].replace(/\\(.)/g, '$1') : null
}

function parseCall(part) {
  const m = part.match(/^(\w+)\((.*)\)$/s)
  if (!m) return { method: part.trim(), args: '' }
  return { method: m[1], args: m[2] }
}

function locatorToSelector(method, args) {
  switch (method) {
    case 'getByRole': {
      const role = firstStringArg(args) || ''
      const name = namedOptionArg(args, 'name')
      const base = ROLE_TO_CSS[role] || `[role="${escAttr(role)}"]`
      return name ? hasText(base, name) : base
    }
    case 'getByText':
      return `text=${firstStringArg(args) || ''}`
    case 'getByLabel': {
      const text = escAttr(firstStringArg(args) || '')
      return `[aria-label="${text}"], label:has-text("${text}") input, label:has-text("${text}") textarea, label:has-text("${text}") select`
    }
    case 'getByPlaceholder':
      return `[placeholder="${escAttr(firstStringArg(args) || '')}"]`
    case 'getByAltText':
      return `[alt="${escAttr(firstStringArg(args) || '')}"]`
    case 'getByTitle':
      return `[title="${escAttr(firstStringArg(args) || '')}"]`
    case 'getByTestId':
      return `[data-testid="${escAttr(firstStringArg(args) || '')}"]`
    case 'locator':
      return firstStringArg(args) || ''
    default:
      return null
  }
}

// Resolve a `page.`-rooted chain (leading `page` already stripped) into the
// selector it targets plus the trailing action call, e.g.
// ['getByRole(\'button\', { name: \'Submit\' })', 'click()'] →
// { selector: 'button, ...:has-text("Submit")', action: 'click', actionArgs: '' }
function resolveChain(parts) {
  let selector = null
  let action = null
  let actionArgs = ''
  const notes = []
  for (const part of parts) {
    const { method, args } = parseCall(part)
    if (LOCATOR_METHODS.has(method)) {
      const sel = locatorToSelector(method, args)
      selector = selector ? `${selector} ${sel}` : sel
    } else if (MODIFIER_METHODS.has(method)) {
      notes.push(`.${method}() ignoré (l'import cible la première correspondance)`)
    } else {
      action = method
      actionArgs = args
    }
  }
  return { selector, action, actionArgs, notes }
}

function actionToStep(action, argsAfterSelector, selector, notes) {
  switch (action) {
    case 'click':
    case 'check':
    case 'uncheck':
    case 'dblclick':
      return { step: { type: 'click', params: { selector } }, notes }
    case 'fill':
      return { step: { type: 'fill', params: { selector, value: firstStringArg(argsAfterSelector) || '' } }, notes }
    case 'type':
    case 'pressSequentially':
      return { step: { type: 'type', params: { selector, text: firstStringArg(argsAfterSelector) || '' } }, notes }
    case 'press':
      return { step: { type: 'press', params: { selector, key: firstStringArg(argsAfterSelector) || 'Tab' } }, notes }
    case 'selectOption': {
      const value = firstStringArg(argsAfterSelector)
        ?? namedOptionArg(argsAfterSelector, 'label')
        ?? namedOptionArg(argsAfterSelector, 'value')
        ?? ''
      return { step: { type: 'select', params: { selector, value } }, notes }
    }
    case 'hover':
      return { step: { type: 'hover', params: { selector } }, notes }
    case 'waitFor':
      return { step: { type: 'wait_element', params: { selector, state: 'visible', timeout: 5000 } }, notes }
    default:
      return { warning: `.${action}() non supporté, étape ignorée`, notes }
  }
}

function directPageCall(method, args) {
  switch (method) {
    case 'goto':
      return { step: { type: 'navigate', params: { url: firstStringArg(args) || '' } } }
    case 'waitForTimeout':
      return { step: { type: 'wait_time', params: { duration_ms: parseInt(args, 10) || 1000 } } }
    case 'waitForSelector':
      return { step: { type: 'wait_element', params: { selector: firstStringArg(args) || '', state: 'visible', timeout: 5000 } } }
    case 'click':
    case 'fill':
    case 'type':
    case 'press':
    case 'selectOption':
    case 'hover':
    case 'check':
    case 'uncheck': {
      const bits = splitTopLevel(args, ',')
      const selector = firstStringArg(bits[0] || '') || ''
      const rest = bits.slice(1).join(',')
      return actionToStep(method, rest, selector, [])
    }
    default:
      return { warning: `page.${method}() non supporté, étape ignorée` }
  }
}

function parseExpectStatement(stmt) {
  const openIdx = stmt.indexOf('(')
  const closeIdx = findMatchingParen(stmt, openIdx)
  if (closeIdx === -1) return { warning: 'assertion illisible, ignorée' }
  const inner = stmt.slice(openIdx + 1, closeIdx).trim()
  const rest = stmt.slice(closeIdx + 1)
  const restMatch = rest.match(/^\.(\w+)\((.*)\)$/s)
  if (!restMatch) return { warning: 'assertion illisible, ignorée' }
  const matcher = restMatch[1]
  const margs = restMatch[2]

  if (inner === 'page') {
    if (matcher === 'toHaveURL') {
      const url = firstStringArg(margs)
      if (url == null) return { warning: 'expect(page).toHaveURL(regex) non littéral, ignoré' }
      return { step: { type: 'assert_url', params: { expected: url, mode: 'equals' } } }
    }
    return { warning: `expect(page).${matcher}() non supporté, ignoré` }
  }

  if (!inner.startsWith('page.')) return { warning: 'assertion sur une cible non reconnue, ignorée' }
  const chainParts = splitTopLevel(inner, '.').slice(1)
  const { selector, notes } = resolveChain(chainParts)
  if (!selector) return { warning: 'sélecteur non reconnu dans une assertion, ignorée' }

  if (matcher === 'toBeVisible') {
    return { step: { type: 'assert_visible', params: { selector } }, notes }
  }
  if (matcher === 'toContainText') {
    const text = firstStringArg(margs)
    if (text == null) return { warning: 'toContainText(regex) non littéral, ignoré' }
    return { step: { type: 'assert_text', params: { selector, expected: text, mode: 'contains' } }, notes }
  }
  if (matcher === 'toHaveText') {
    const text = firstStringArg(margs)
    if (text == null) return { warning: 'toHaveText(regex) non littéral, ignoré' }
    return { step: { type: 'assert_text', params: { selector, expected: text, mode: 'equals' } }, notes }
  }
  return { warning: `.${matcher}() non supporté, ignoré`, notes }
}

function parseStatement(stmt) {
  if (stmt.startsWith('expect(')) return parseExpectStatement(stmt)
  if (!stmt.startsWith('page.')) return { warning: 'instruction non reconnue, ignorée' }

  const parts = splitTopLevel(stmt, '.').slice(1)
  if (parts.length === 1) {
    const { method, args } = parseCall(parts[0])
    return directPageCall(method, args)
  }
  const { selector, action, actionArgs, notes } = resolveChain(parts)
  if (!selector || !action) return { warning: 'instruction non reconnue, ignorée' }
  return actionToStep(action, actionArgs, selector, notes)
}

/**
 * Parse a `playwright codegen` script (raw JS/TS source) into ScenarioBuilder
 * steps. Best-effort: unrecognized statements are skipped and reported as
 * warnings rather than aborting the whole import.
 *
 * @param {string} source
 * @returns {{ steps: Array<{type: string, params: object}>, warnings: string[], statementCount: number }}
 */
export function parsePlaywrightScript(source) {
  const steps = []
  const warnings = []
  let statementCount = 0

  for (const rawLine of String(source).split('\n')) {
    const m = rawLine.match(/^\s*await\s+(.+?);\s*$/)
    if (!m) continue
    statementCount++
    const stmt = m[1].trim()
    const result = parseStatement(stmt)
    if (result.step) steps.push(result.step)
    if (result.warning) warnings.push(result.warning)
    if (result.notes?.length) warnings.push(...result.notes)
  }

  return { steps, warnings, statementCount }
}
